### ISSUE TITLE
Converting "imgs_mask_test.npy" into image format

### ISSUE THREAD

**Issue by iamrosmarin** [jocicmarko/ultrasound-nerve-segmentation#10]
Hi Marko,

First of all, thanks for sharing your code in this repository. It has been really useful for the project I am doing: segmentation of skin lesions.

I have run all your code, and I already have the "imgs_mask_test.npy" file but I would like to convert this numpy array file into tiff/png/jpeg images. Do you have a code for doing that?

Thanks in advance.

**Comment by jocicmarko** [comment]
You could iterate through that array and save each image on disk with ```imwrite()``` function. Both OpenCV and scikit-learn have this function, but you should look it up for more details.

**Comment by iamrosmarin** [comment]
Thanks for your quick reply, Marko! 

Furthermore, when I create the .npy files with the function data.py, all of them (imgs_test, imgs_train, imgs_train_mask) are empty:

array([[[[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
...,
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0]]],

What do you think about it?

**Comment by jocicmarko** [comment]
I guess that you should rescale the masks from real [0,1] interval (because of the sigmoid activation) to discrete [0,255] integer interval before saving the image.

**Comment by iamrosmarin** [comment]
Thank you for your help.

Finally I am using this file to convert the numpy arrays into images.

**Comment by iamrosmarin** [comment]
import numpy as np
from scipy.misc import toimage, imsave
import os

# in_dir = "imgs_train"
in_dir = "imgs_test"
# in_dir = "imgs_mask_test"
# in_dir = "imgs_mask_train"

images_to_convert_path = './' + in_dir + '.npy'

img_array = np.load(images_to_convert_path)

output_dir = 'binary_image'

# these are the selected 'random' 5 images to test
# names will be matched by index for now: 1=22, 2=234...
list_of_random_index = [1, 354, 453, 599, 844]

#  output directory
def ensure_directory_exist(directory_name):
    exist_bool = os.path.isdir('./' + directory_name)
    if not exist_bool:
        os.mkdir(directory_name)

# use this to show the image rather than save it, if you want
def show_image(image):
    toimage(image).show()

# save the image array to a .png file
def plot_image_save_to_file(name, img_cur):
    #  ensure a directory is present/build if necessary
    save_directory = output_dir  # from global value
    ensure_directory_exist(save_directory)

    #  build full path and save
    file_name = name + '.png'
    full_path = os.path.join(save_directory, file_name)
    imsave(full_path, img_cur)

# convert the numpy array to a int array through .astype('float32')
def convert_numpy_array_to_int_array(img_array):
    print(len(img_array))   # will return number of pictures
    image_list = []
    i = 0
    while i < len(img_array):
        for photo_indiv in img_array[i]:
            image = photo_indiv.astype('float32')
            image_list.append(image)
            # plot_image_save_to_file("jack", image)
            # print(image)
        i += 1
    return image_list

# loop through converted int array and save the image to .png
def convert_int_array_to_png(image_list):
    ind_id = 1
    for photo_array in image_list:
        name = in_dir + '_' + str(ind_id)
        plot_image_save_to_file(name, photo_array)
        ind_id += 1

# create a list of 5 int image array
def get_random_5(img_array_int):
    mySet = set()
    smaller_list = []

    for selected_index in list_of_random_index:
        mySet.add(selected_index)

    i = 0
    while i < len(img_array_int):
        if i in mySet:
            smaller_list.append(img_array_int[i])
        i += 1

    return smaller_list

# wrapper to create 5 'random'(spec. gloablly) .png files to view binary mask
def convert_random_5(img_array_int):
    smaller_list = get_random_5(img_array_int)
    convert_int_array_to_png(smaller_list)

# main wrapper
def main():
    img_array_int = convert_numpy_array_to_int_array(img_array)
    convert_random_5(img_array_int)  # TODO: make sure naming matches
    # convert_all_images(img_array_int) # DONT RUN THIS
main()

**Comment by jocicmarko** [comment]
Cool! Glad you had it worked out ;)

**Comment by MariyaBaby** [comment]
Hey, @iamrosmarin , for the above code by @jocicmarko , did you get the test_masks as images classified and localised correctly? Please let me know. After running the code, the got the imgs_mask_test.npy file. And i converted the .npy to png file.But the test_mask for every test image is shown the same. IS it due to the conversion to image or due to the error in train model?

**Comment by iamrosmarin** [comment]
Hi @MariyaBaby . As far as I know, your `imgs_mask_test.npy` file should include all numpy arrays of your test images. i.e. for 400 testing images the `imgs_mask_test.npy` would have 400 numpy arrays (matrices). So I bet you have some error in your train model. I can help you with your code if you want. Just contact me at _adriaromero@me.com_ . Cheers.

**Comment by MariyaBaby** [comment]
Hello @iamrosmarin can you explain why in the get_unet(), the merge([UpSampling2D]) is done,? The model why it is created with 10 layers? Can you please explain the model? Thank you so much in advance .. I'm just a beginner in CNN.

**Comment by MariyaBaby** [comment]
Also, @iamrosmarin , @jocicmarko  how's the evaluation done?

**Comment by soon-will** [comment]
hi,thank you for your code.i ran your code ,but had a problem.i really need your help.the mistake is like this:
ValueError: 'arr' does not have a suitable array shape for any mode.

**Comment by conanhung** [comment]
Hi, for me, to see the images in img_mask_test.npy as black and white image, I had to change the function:

# convert the numpy array to a int array through .astype('float32')
def convert_numpy_array_to_int_array(img_array):
    print(len(img_array))   # will return number of pictures
    image_list = []
    i = 0
    while i < len(img_array):
        for photo_indiv in img_array[i]:
            image = photo_indiv.astype('float32')
            image_list.append(image)
            # plot_image_save_to_file("jack", image)
            # print(image)
        i += 1
    return image_list

to:

# convert the numpy array to a int array through .astype('float32')
def convert_numpy_array_to_int_array(img_array):
    print(len(img_array))   # will return number of pictures
    image_list = []
    i = 0
    while i < len(img_array):
        for photo_indiv in img_array[i]:
            image = photo_indiv.astype('float32')
            image = image*255 # NOTE: for imgs_mask_test, the pixel value should be multiplied by 255
            image_list.append(image)
            # plot_image_save_to_file("jack", image)
            # print(image)
        i += 1
    return image_list

Hope this help!

**Comment by soon-will** [comment]
hi,  @conanhung .thank you for your code. i tried that,but also got a mistake like this:ValueError: 'arr' does not have a suitable array shape for any mode.do you know how to solve that?thank you!

**Comment by conanhung** [comment]
Can you check if the input .npy is correct? How about its shape?

Also, try this code: https://github.com/conanhung/ultrasound-nerve-segmentation/blob/master/view_mask_test.py

To run the code, you have to install OpenCV 2 with python.

**Comment by soon-will** [comment]
hi, @conanhung  Thank you for your help.I have checked that.The input .npy is (5308,2) which is not (5308,32,32,1)like your input.In fact,I want transform the ".csv" file that I get finally to "tif" or "jpg".Could you please share some code about that?eg,transform the "train_mask.csv"to "tif".

**Comment by soon-will** [comment]
thanks a lot!do you know that how to transform the "train_masks.csv"that the competion offered to "train_mask.jpg"?is there any code to share?thank you very much~

**Comment by soon-will** [comment]
@jocicmarko thanks a lot!do you know that how to transform the "train_masks.csv"that the competion offered to "train_mask.jpg"?is there any code to share?thank you very much~
