### ISSUE TITLE
regarding fitting the image set with different channel size to this framework

### ISSUE THREAD

**Issue by huaiyanggongzi** [jocicmarko/ultrasound-nerve-segmentation#12]
Hello Marko, 

The code you posted is very clean and well-written. Thank you!  If I have an image training set with input channel as 3, how can I fit this set to your framework. Looks like the Kaggle set has training set with channel=1.

Huaiyanggongzi

**Comment by jocicmarko** [comment]
Hi Huaiyanggongzi,

yes, Kaggle images have only 1 channel, but if you wanted to use this model for images with 3 channels (RGB pictures), make sure you change the line ```inputs = Input((1, img_rows, img_cols))``` to ```inputs = Input((3, img_rows, img_cols))```.

Marko
