### ISSUE TITLE
let u-net predict images having different size with training images

### ISSUE THREAD

**Issue by wenouyang** [jocicmarko/ultrasound-nerve-segmentation#17]
Hi Marko,

I have limited number (around 500~700) images with large size (1024*1024). I constructed large amount of training set based on sampling from original images. The sampled size is 128*128.  I trained a model, and then tried to predict over the test images (1024*1024). Previously, I just make prediction over the sub-frame of the test images, and then stitch these predicted masked together. 

I heard that there is a way to let trained network can predict any size of images. The trick is replacing `inputs = Input((1, img_rows, img_cols))` to `inputs = Input((1, None, None))`. I tried, but i have error messages as. Do you have any thoughts on this? Or is it possible to let U-net predict images having different size with trained images.

```
Traceback (most recent call last):
  File "train-unet-v3b.py", line 113, in <module>
    train_and_predict()
  File "train-unet-v3b.py", line 96, in train_and_predict
    model = get_unet()
  File "train-unet-v3b.py", line 54, in get_unet
    up6 = merge([UpSampling2D(size=(2, 2))(conv5), conv4], mode='concat', concat_axis=1)
  File "/development/gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/development/gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/development/gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/development/gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/layers/convolutional.py", line 1043, in call
    self.dim_ordering)
  File "/development/gtfw/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/backend/tensorflow_backend.py", line 508, in resize_images
    X.set_shape((None, None, original_shape[2] * height_factor, original_shape[3] * width_factor))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

```

**Comment by jocicmarko** [comment]
Hi,

yes, since the U-net is fully-convolutional model, it should be able to run on any image size in test time. Which backend to you use? Tensorflow usually doesn't like these ```None``` when defining a model.

**Comment by wenouyang** [comment]
Hi, 

I am using Tensorflow. 

Another possible approach is that I scale the test image(1024*1024) to the size of training image (128*128). After making the prediction, I scale it back. Does it make sense, or does it have any potential issue? Thanks.

**Comment by jocicmarko** [comment]
Well, an obvious issue is that after rescaling from 128x128 to 1024x1024, you will actually only increase resolution, whereas quality of the image will stay low. Also, this way your model will probably fail to capture fine details.

**Comment by srishti26** [comment]
Hi ,
I am using Theano backend but when i ran this code it got stuck on epoch and not running further. Even it is not getting terminated and also no error message is there. Can you help me with this?
Thanks

**Comment by jocicmarko** [comment]
@srishti26 actually I can't, sorry... :( A year ago I remember I managed to get it working, but it included some hacks and changes to the source code. If I manage to dig up that code, I will share it here.

**Comment by umtbudak** [comment]
Hi **[@jocicmarko]**<https://github.com/jocicmarko>  my images size are 600×600. I want to test 600×600 size img_row and img_col. But

**Comment by mrgloom** [comment]
Even if you manage to put large image directly to U-net it will hit GPU VRAM limit, so people cut large image in reasonable size tiles with overlap and then merge results.
