### ISSUE TITLE
training with images of different size

### ISSUE THREAD

**Issue by wenouyang** [jocicmarko/ultrasound-nerve-segmentation#19]
In another thread, you were discussing whether U-net can predict images with different sizes. If in the training stage, I am also trying to feed U-net with images of different size, can I do it with the current U-net implementation, (or just use **None** in the input layer)? Thanks.

**Comment by jocicmarko** [comment]
I don't think that would be possible, since during training the tensors that are passed between layers in each batch must have fixed size.

**Comment by mrgloom** [comment]
You can try to use Spartial Pyramid Pooling layer: https://github.com/yhenon/keras-spp
But anyway size of images in the batch should be the same and training will be slower because of network constant blob reshaping.
