### ISSUE TITLE
UpSampling

### ISSUE THREAD

**Issue by gravity1989** [jocicmarko/ultrasound-nerve-segmentation#2]
Hi,

I think in the paper, we are required to performed a "learned upsampling" or a "convolution transpose".

However, the implementation here uses UpSampling2D.
https://github.com/jocicmarko/ultrasound-nerve-segmentation/blob/master/train.py#L51

Any comments on this?

Rahul.V.

**Comment by pengpaiSH** [comment]
+1 I am also a little bit confused about UpSampling and so-called "deconvolution".

**Comment by jocicmarko** [comment]
Keras doesn't have "learned upsampling" or "deconvolutions" (at least for now), so I just used basic upsampling - my solution is just loosely inspired by U-net. However, I've seen somewhere online a Keras implementation of this, but I can't remember where exactly - you can Google it.

Also, feel free to contribute with your own implementations ;).

**Comment by pengpaiSH** [comment]
@jocicmarko Marko, thank you for your reply! I have one question and ask for you help. I have made a few minor modifications based on your provided codes. And my local validation score is nearly 0.59. However, my score on the LB is 0.52. There is always a big gap between validation and LB.

Note that I didn't install opencv. Thus I change the **prep** function based on scipy.misc.

```
from scipy.misc import imresize
def prep(img):
    img = img.astype('float32')
    #img = cv2.threshold(img, 0.5, 1., cv2.THRESH_BINARY)[1].astype(np.uint8)
    img[img <= 0.5] = 0.
    img[img > 0.5] = 1.
    img = img.astype(np.uint8)
    img = imresize(img, size = (image_rows, image_cols))
    return img
```

Any thoughts?

**Comment by jocicmarko** [comment]
@pengpaiSH you should look int scipy documentation for imresize, as it works somewhat specifically (I think it rescales values, if I remember correctly)

**Comment by nikhilshinday** [comment]
Hey, just so you know, Keras now supports deconvolution, making the weights trainable.
[Here's](https://keras.io/layers/convolutional/#conv2dtranspose) the method that should be used instead of UpSampling2D

**Comment by mrgloom** [comment]
@pengpaiSH I'm not sure but scipy and opencv image read functions have different channels order RGB vs BGR, so it' maybe bad idea to mix these packages.
