### ISSUE TITLE
Quick question about training batch and testing

### ISSUE THREAD

**Issue by 32nguyen** [jocicmarko/ultrasound-nerve-segmentation#34]
Hi, 
I have a basic question about keras implementation. Assuming I train with batch, for example, (batch_size = 64, image_size, image_size), slipped from training, for example (10000, image_size, image_size). My test_data (4000, image_size, image_size).
I would like to know when running model.predict(test_data), keras will split the test_data in to batch 64 to evaluate with iteration, or it evaluates with whole stack?

and if I pass the single images in test_data one by one, is there any changes?

Thank guys
Bests,

**Comment by nikhilshinday** [comment]
Looking at [Keras documentation](https://keras.io/models/model/#predict), it looks like `batch_size=32` by default. Just include your batch size as a parameter when predicting.

**Comment by 32nguyen** [comment]
Ty so much.
