### ISSUE TITLE
regarding train.py

### ISSUE THREAD

**Issue by Guru-prasad** [jocicmarko/ultrasound-nerve-segmentation#35]
Hi jocicmarko , thanks for sharing the code
i m new born to this deep learning.
while executing train.py , i am getting following warning which is not allowing to complete execution.

> C:\Anaconda3\lib\site-packages\skimage\transform\_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.

python version-3.5
scikit-image-0.13.0

any help is appreciated a lot........!

**Comment by jocicmarko** [comment]
@Guru-prasad this code is tested on Python 2.7, and it seems you are running Python 3.5
