### ISSUE TITLE
some question about preprocessing

### ISSUE THREAD

**Issue by soon-will** [jocicmarko/ultrasound-nerve-segmentation#38]
Hi, jocicmarko. While reading your code, I have some question. You scale imgs_mask to [0,1], while you preprocess your imgs like that ```x-=np.mean   x/=np.std```.I want to know the reason why you don't preprocess your imgs and imgs_mask like that ```x-=np.mean   x/=np.std```.Thank you for your replying

**Comment by jocicmarko** [comment]
Hi @soon-will , the masks are just scaled to [0,1] interval, because then they are suitable for training and prediction -> sigmoid layer outputs values in [0,1] interval.
