### ISSUE TITLE
Question about Dice function

### ISSUE THREAD

**Issue by qinxi117** [jocicmarko/ultrasound-nerve-segmentation#53]
Your code works very well, and I have been using and also modified for many projects.
However i just realized today that Dice and IOU are both non-differentiable function.
Then my question is, why it works in your code?
Thanks!

**Comment by jocicmarko** [comment]
It's actually possible to make them differentiable. Dice and IoU both use intersection and union (which work basically with sets), but these can be approximated in real domain with \* and \+ if you make sure your outputs are in range [0,1].

**Comment by qinxi117** [comment]
Yeah, you are right, I also searched for answers on google. Somebody did indicated the output shoud be within[0,1], and somebody else propose some 'soft' dice.
But I still don't quite understand why. I know this is definitely right, but I really need a example or some fomula.
Can you explain more details or are there some papers I can refer to?

Thanks!

**Comment by jocicmarko** [comment]
I'm not aware if there is a paper or some resource which I can refer you to.
However, usually when I find myself in such confused state, I take a very simple example and do everything by hand.
I suggest you make up binary 3x3 mask and 3x3 prediction that is slightly off (i.e. 1 pixel wrong). Then derive gradients of Dice loss and you should be able to see more clearly what's going.
Of course, this takes time, but once you get it right you know it for life :).

**Comment by qinxi117** [comment]
@jocicmarko Ok, I'll try it. Thank you very much
