### ISSUE TITLE
couldn't understand train.py size of images

### ISSUE THREAD

**Issue by sudhabg** [jocicmarko/ultrasound-nerve-segmentation#69]
Couldn't understand the image size in train.py
Image is resized to 96 x 96 when in the readme it says 64 x 80. but the actual size is 520 x 480 pixels with dpi 96 x 96. So is the dpi mapped to the pixels? Please explain
img_rows = 96
img_cols = 96

**Comment by jocicmarko** [comment]
The actual image and mask size is 96x96. The documentation (README) wasn't updated accordingly. It now is, thank you for reporting this.

**Comment by sudhabg** [comment]
Thanks for the response and updating it.
