### ISSUE TITLE
Help me solve this error

### ISSUE THREAD

**Issue by AlexandruHodrogea** [jocicmarko/ultrasound-nerve-segmentation#7]
Exception                                 Traceback (most recent call last)
<ipython-input-17-ad0103fd719c> in <module>()
----> 1 up6 = merge([UpSampling2D(size=(2, 2, 2), dim_ordering='default')(conv5), conv4], mode='concat', concat_axis=1)

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in merge(inputs, mode, concat_axis, dot_axes, output_shape, output_mask, name)
   1526                             node_indices=node_indices,
   1527                             tensor_indices=tensor_indices,
-> 1528                             name=name)
   1529         return merge_layer.inbound_nodes[0].output_tensors[0]
   1530     else:

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in __init__(self, layers, mode, concat_axis, dot_axes, output_shape, output_mask, node_indices, tensor_indices, name)
   1184             self._arguments_validation(layers, mode,
   1185                                        concat_axis, dot_axes,
-> 1186                                        node_indices, tensor_indices)
   1187             self.built = True
   1188             self.add_inbound_node(layers, node_indices, tensor_indices)

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in _arguments_validation(self, layers, mode, concat_axis, dot_axes, node_indices, tensor_indices)
   1251                 raise Exception('"concat" mode can only merge layers with matching ' +
   1252                                 'output shapes except for the concat axis. ' +
-> 1253                                 'Layer shapes: %s' % (input_shapes))
   1254 
   1255     def call(self, inputs, mask=None):

Exception: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 0, 8, 512), (None, 0, 8, 256)]

**Comment by jocicmarko** [comment]
It could be two things:

- you are using TensorFlow dimension ordering (in this tutorial I assumed Theano dimension ordering)
- sizes of your input images are wrong

If it's neither of these two, you should post your code here in order to debug it.

**Comment by markeroon** [comment]
@jocicmarko Yes, if you switch your image_dim_ordering to 'th' in keras.json then this problem goes away. Thanks for this example, btw.

**Comment by jocicmarko** [comment]
I updated the code to use Theano dimension ordering by default.
@AlexandruHodrogea try if it works now
