### ISSUE TITLE
regarding the difference between mask image channel and output layer channel

### ISSUE THREAD

**Issue by surfreta** [jocicmarko/ultrasound-nerve-segmentation#8]
Hi Marko,

Thank you for sharing the code.

I have two questions while reading your code.

1) The input mask images have channel 1, while the output layer(or the prediction) from U-net is of channel 2. How does your code handle this kind of scenario?
After reading your code, I have not been very clear about the mechanism you use for handling this.

2) I am not very clear about the usages of this function

`def preprocess(imgs):
    imgs_p = np.ndarray((imgs.shape[0], imgs.shape[1], img_rows, img_cols), dtype=np.uint8)
    for i in range(imgs.shape[0]):
        imgs_p[i, 0] = cv2.resize(imgs[i, 0], (img_cols, img_rows), interpolation=cv2.INTER_CUBIC)
    return imgs_p`

I can see this code is used to transform the mask images, but I do not know why?

Thank you very much for your help.

**Comment by jocicmarko** [comment]
Hi,

>The input mask images have channel 1, while the output layer(or the prediction) from U-net is of channel

In the original U-net they used 2 output channels, with softmax activation and log-loss. Background and foreground are represented as 2 classes, thus 2 channels, 1 for each.

> How does your code handle this kind of scenario?

In my solution, I didn't use softmax activation and log-loss, but sigmoid activation and Dice score as loss. Basically, authors of original U-net defined the problem as 2-class segmentation (background class and foreground class), while I defined it as binary segmentation (only foreground).

> I am not very clear about the usages of this function

That preprocessing function just resizes the images to manageable size, as original images were to big  and thus memory consuming.

**Comment by surfreta** [comment]
Thanks a lot.
